### ISSUE TITLE
On-demand loading

### ISSUE THREAD

**Issue by Dupond** [lambdalisue/vim-suda#28]
Hello,

Is there a way to load the plugin on-demand? It's an option that is provided by a few plugin managers, e.g. [vim-plug](https://github.com/junegunn/vim-plug), allowing you to load a plugin that way:
```
Plug 'junegunn/vim-github-dashboard', { 'on': ['GHDashboard', 'GHActivity'] }
```

The `on` parameter specifies which function of the plugin triggers the loading.

However, I can't seem to succeed in applying this method to suda, which is a *relatively* slow plugin to load (compared to the other plugins that I use, I mean; suda takes about 30ms to load according to `vim --startuptime`).

So the idea would be to only load `suda` when needed (that is, when a file is saved using this plugin)... Any idea?

Any help would be greatly appreciated!

Best regards,
Dupond

**Comment by MadeOfMagicAndWires** [comment]
The problem is that you don't directly call a command (like `:GHDashboard`) that would trigger autoloading.

You could possibly install this as an optional plugin using the native package manager, then map something to `packadd! suda`.

Other than that I don't think `'on'` and '`for`' are useable because this plugin isn't just used for a specific trigger command or filetype.

**Comment by Dupond** [comment]
OK, thanx for the explanation.
